CPMAddPackage(
  EXCLUDE_FROM_ALL YES
  GIT_REPOSITORY "https://github.com/CLIUtils/CLI11"
  GIT_TAG v2.3.2
  NAME CLI11
  OPTIONS
  "CLI11_BUILD_EXAMPLES OFF"
  "CLI11_BUILD_TESTS OFF"
  "CLI11_BUILD_DOCS OFF"
)
